{
    extends: [
        "stylelint-config-standard",
        "stylelint-config-prettier",
        "stylelint-prettier/recommended"
    ],
    plugins: ['stylelint-sass'],
    overrides: [{ files: ['**/*.sass'], customSyntax: 'postcss-sass' }]
}
